MSIT141Site/Models/ErrorViewModel.cs
using System;

namespace MSIT141Site.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MSIT141Site/Controllers/HWController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSIT141Site.Controllers
{
    public class HWController : Controller
    {
        public IActionResult HW1()
        {
            return View();
        }
    }
}

MSIT141Site/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MSIT141Site.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MSIT141Site.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }     
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MSIT141Site/Views/HW/HW1.cshtml
<button class="btn btn-primary mb-3" type="button" id="buttonClick">Create</button>

<div id="iddiv">
    <table class="table table-striped table-hover" id="idtable">
    </table>
</div>

@section Scripts
{
    <script>document.querySelector("#buttonClick").addEventListener("click", CreateTable);
        function CreateTable() {
            var emp = {
                "employees": [
                    { "name": "Tom", "workYears": 3, "salary": 35000 },
                    { "name": "Jack", "workYears": 5, "salary": 40000 },
                    { "name": "Mary", "workYears": 7, "salary": 45000 }
                ]
            };

            Add("Name", "WorkYears", "Salary");

            emp.employees.forEach(employees => {
                const { name, workYears, salary } = employees;
                Add(name, workYears, salary);
            })
        }

        function Add(name, workYears, salary ) {
            let theTable = document.querySelector("#idtable");
            let eletr = document.createElement("tr");
            let eletdn = document.createElement("td");
            let eletdw = document.createElement("td");
            let eletds = document.createElement("td");

            let txtname = document.createTextNode(name);
            let txtworkYears = document.createTextNode(workYears);
            let txtsalary = document.createTextNode(salary);

            eletdn.appendChild(txtname);
            eletdw.appendChild(txtworkYears);
            eletds.appendChild(txtsalary);
            eletr.appendChild(eletdn);
            eletr.appendChild(eletdw);
            eletr.appendChild(eletds);
            theTable.appendChild(eletr);
        }</script>


}

MSIT141Site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Styles
{
    <style>
        h1.change {
            background-color: aliceblue;
        }
    </style>

}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a></p>
</div>

<button class="btn btn-primary mb-3" type="button" id="buttonClick">Create</button>


@section Scripts
{
    <script>
        
        const btn = document.querySelector('#buttonClick');
        const myH = document.querySelector('.display-4');
       
        btn.addEventListener('click', () => {
          
            myH.textContent = "Welcome MVC!!";
            $('.display-4').text("Welcome MVC!!").css("background-color", "aqua");

    
            var emps = [{ "name": "Tom", "workYears": 3, "salary": 35000 },
            { "name": "Jack", "workYears": 5, "salary": 40000 },
            { "name": "Mary", "workYears": 7, "salary": 45000 }];
            //[{},{},{}]
            //array[index 0,1,2]
            //const emp = emps[1] //{ "name": "Jack", "workYears": 5, "salary": 40000 }
            ////object.prop  emp.name => Jack
            //myH.textContent = emp.salary
 
            //for (let i = 0, max = emps.length; i < max; i++) {
            //    console.log(emps[i].name)
            //    console.log(emps[i].workYears)
            //    console.log(emps[i].salary)
            //}

            var emp = {
                "employees": [
                    { "name": "Tom", "workYears": 3, "salary": 35000 },
                    { "name": "Jack", "workYears": 5, "salary": 40000 },
                    { "name": "Mary", "workYears": 7, "salary": 45000 }
                ]
            };
            for (let i = 0; i < emp.employees.length; i++) {
                //console.log(emps[i].name)
                //console.log(emps[i].workYears)
                //console.log(emps[i].salary)
            }

            emp.employees.forEach(employees => {
                const { name, workYears, salary } = employees;
                console.log(name);
                console.log(workYears);
                console.log(salary);
            })
        });


        $("#buttonClick").on("click", function () {
            var emp = {
                "employees": [
                    { "name": "Tom", "workYears": 3, "salary": 35000 },
                    { "name": "Jack", "workYears": 5, "salary": 40000 },
                    { "name": "Mary", "workYears": 7, "salary": 45000 }
                ]
            };
            $.each(emp.employees, (idx, employee) => {
                const { name, workYears, salary } = employee
                console.log(name)
                console.log(workYears)
                console.log(salary)
            })
        })

    </script>


}

MSIT141Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MSIT141Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MSIT141Site</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HW" asp-action="HW1">HoneWork</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MSIT141Site - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>